name: Inclusive Naming, Lint
on: [pull_request]

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"
  call-lint-and-unit:
    name: Inclusive Naming
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main
    with:
      with-uv: true
